### ISSUE TITLE
Incremental Schema Generation

### ISSUE THREAD

**Issue by skorfmann** [Armkit/armkit#14]
Let's do the schema generation in incremental steps. 

We could add a `schema-config.json` and define the targets for the schema generator:

```
{
  "buildTargets": [
    "Microsoft.ContainerService"
  ]
}
```

By default, we'll assume `latest` as the version. We could support specifying the version like this:

```
{
  "buildTargets": [
    "Microsoft.ContainerService@2019-06-01"
  ]
}
```

This will allow to add schemas one by one. That's gonna be way easier than making sure that all the schemas are compiling at once.

## Implementation

The generator / import step will have to do the following steps:
 
- Build the full Schema except `resources`
- Build `Common`
- Build the build targets from the config files

In the first step, we should just make sure it compiles. 

For a full example, we'll have to make sure that it's actually deployable. This doesn't have to work right away, though.

## Prerequisites

- Refactoring of CLI importer 
- Fully understand the versioning of the schema

**Comment by skorfmann** [comment]
What's the URL for the full Schema again? @aheumaier

**Comment by aheumaier** [comment]
https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#
