### ISSUE TITLE
Armkit installation error

### ISSUE THREAD

**Issue by ElYusubov** [Armkit/armkit#32]
When trying the GitHub instructions to install Armkit, it throws an error:

steps to reproduce the behavior:
1. Checked the npm and node versions (NodeJS > 12.6 and npm - 6.14.4)
2. Type "npm i -g armkit"
3. See error screenshot
![image](https://user-images.githubusercontent.com/29330538/105072506-e4107000-5a53-11eb-8b6e-b11b89b978e0.png)

**Expected behavior**
Installation should succeed.

**Desktop (please complete the following information):**
 - Device: Laptop Win 10
 - OS: Win 10 Enterprise
 - Version: NodeJS > 12.6 & npm - 6.14.4

**Comment by aheumaier** [comment]
Hi @ElYusubov, Thanks for bringing this up!  There are no published packaged at the moment. I will add a development section in the meantime . Our current working branch is `development` until we going to do a first release.

Until now to get started do :

1.)  Go to development branch 
2.) install dependencies at root level with `yarn install` 
3.) build armkit packages at root level with `yarn build`
4.) Go to `examples/basic`
5.) `yarn generate` builds your libs in `examples/basic/.generated`
6.) run `yarn build` here again to  translate `index.ts` to `index.js`
7.) run `node index.js` to see `ndex.js` translate into an ARM template in `examples/basic/cdkout/helloarmkit.json`
8.) deploy the example with `az deployment group create --resource-group rg-my-resource-group --template-file cdk.out/helloarmkit.json`

**Comment by ElYusubov** [comment]
Thanks for response, I will follow up with instructions.

Thanks,
EL

________________________________

**Comment by aheumaier** [comment]
Updated docs, also adding contributer guide.
Closed in #33

**Comment by ElYusubov** [comment]
If you still get some build issues, try the following steps:

![image](https://user-images.githubusercontent.com/29330538/105538204-0eb33080-5cc1-11eb-8598-7be4ab12ecb8.png)
