### ISSUE TITLE
Build fails on initial repo clone

### ISSUE THREAD

**Issue by CodeRunRepeat** [Armkit/armkit#42]
The initial `yarn build` on a freshly cloned repo fails since the .generated files in the basic example are missing. To reproduce, clone the repo in a new directory and run `yarn build`. 
You will get

```
$ tsc
lerna ERR! yarn run build exited 1 in '@examples/basic'
lerna ERR! yarn run build stdout:
$ tsc
index.ts(5,8): error TS2307: Cannot find module './.generated/ContainerInstance'.
index.ts(8,8): error TS2307: Cannot find module './.generated/ContainerRegistry'.
```

To resolve this, one can change the build script for the example to `armkit generate && tsc`, or add a new script, e.g. `bootstrap` that will be used only once, is the same as `build` for the other packages, and will run `armkit generate && tsc` for the example. First approach is simpler, but I am not sure what the overhead of running `generate` each time would be.

**Comment by pgollucci** [comment]
I agree.  I willl have a look.

**Comment by aheumaier** [comment]
resolves in #81 that  updates yarn task deps

**Comment by aheumaier** [comment]
@CodeRunRepeat @tomconte @pgollucci  Does th current changes in main resolves this issue ?

**Comment by aheumaier** [comment]
Feel free to reopen if there should be still issues arise
