### ISSUE TITLE
core: resource - delete props doesn't make sense

### ISSUE THREAD

**Issue by pgollucci** [Armkit/armkit#53]
![arm-resource_ts_—_Untitled__Workspace_](https://user-images.githubusercontent.com/34295/116015294-ac8f0200-a606-11eb-81bf-b20b0789a294.jpg)

Why delete it as soon as it's constructed? If you are going to do that, then the property needs to be optional aka a '?' otherwise the Interface contract is broken hence the typescript error.

**Comment by aheumaier** [comment]
I can remember that addin the "delete" step was resoving an issue and was added by intend.
I asume its just bad design  this could resolved by refactoring though
