### ISSUE TITLE
Sub-service implementations overwrite their parents

### ISSUE THREAD

**Issue by ohthehugemanatee** [Armkit/armkit#74]
**Describe the bug**
We presently build the output filename by splitting the second part of the fqn (e.g. `Microsoft.Compute`, by `.`, and then taking the second part. (e.g. `Compute`). That's fine for most services, but sub-services are also separated by `.` in the fqn. e.g. `Microsoft.Compute.Galleries` will also get the filename `Compute`. It will therefore overwrite the parent implementation. 

This is also why all sub-services fail the snapshot tests added in #68 : the test is looking for a file called `/tmp/KeyVault.Secrets.testQycoiN/KeyVault.Secrets.ts`, when the importer created `/tmp/KeyVault.Secrets.testQycoiN/KeyVault.ts`.

**To Reproduce**
1. Add a sub-service (e.g. `2019-03-01/Microsoft.Compute.Galleries`) to the services fixture.
2. Run tests in `armkit-cli`
3. See error

**Expected behavior**
The filename should account for the entire service name, including sub-services.

This error effects the following services:
```
["2021-03-01/Microsoft.Cache.Enterprise", "Cache.Enterprise"],
["2016-10-01/Microsoft.StorSimple.1200", "StorSimple.1200"],
["2021-03-01/Microsoft.RecoveryServices.Backup", "RecoveryServices.Backup"],
["2019-03-01/Microsoft.Compute.Galleries", "Compute.Galleries"],
["2017-06-01/Microsoft.StorSimple.8000", "StorSimple.8000"],
["2021-03-01/Microsoft.RecoveryServices.SiteRecovery", "RecoveryServices.SiteRecovery"],
["2020-12-01/Microsoft.Compute.Extensions", "Compute.Extensions"],
["2016-06-01/Microsoft.RecoveryServices.legacy", "RecoveryServices.legacy"],
["2020-03-01/Microsoft.Devices.Provisioning", "Devices.Provisioning"],
["2020-11-01/Microsoft.Network.FrontDoor", "Network.FrontDoor"],
["2021-03-08/Microsoft.Insights.Application", "Insights.Application"],
["2015-06-01/Microsoft.KeyVault.Secrets", "KeyVault.Secrets"],
```

**Comment by aheumaier** [comment]
Fixed in #81
